- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> [CI] Added ReleaseDrafter workflow

- .github/config.yml
This PR fixes the link to layer-5 celebration image of welcome-bot
> Fix welcome bot image link

- Dockerfile
Signed-off-by: aisuko <urakiny@gmail.com>
We did not push any Docker image to DockerHub and we should fix the issue.
> Fixing the build file

- api/grpc/grpc.go
- internal/config/config.go
- internal/config/keys.go
- main.go
> added env for nats endpoint

- internal/cache/cache.go
Signed-off-by: Uddeshya Singh <singhuddeshyaofficial@gmail.com>
This PR fixes #20
This adds required error handling
> Add error handling in cache package

- .github/workflows/ci.yml
- api/grpc/grpc.go
Signed-off-by: aisuko <urakiny@gmail.com>
> Removed json label

- Makefile
- api/grpc/grpc.go
- go.mod
- go.sum
- internal/cache/cache.go
- internal/cluster/pipeline/deployment.go
- internal/cluster/pipeline/namespace.go
- internal/cluster/pipeline/pipeline.go
- internal/cluster/pipeline/pod.go
- internal/cluster/pipeline/service.go
- internal/meshes/istio/pipeline/pipeline.go
- main.go
- pkg/model/model.go
- pkg/model/model_converter.go
> model fixes

- internal/config/config.go
- internal/meshes/istio/informers/authorization_policy.go
- internal/meshes/istio/informers/destination_rule.go
- internal/meshes/istio/informers/envoy_filter.go
- internal/meshes/istio/informers/gateway.go
- internal/meshes/istio/informers/peer_authentication.go
- internal/meshes/istio/informers/request_authentication.go
- internal/meshes/istio/informers/service_entry.go
- internal/meshes/istio/informers/sidecar.go
- internal/meshes/istio/informers/virtual_services.go
- internal/meshes/istio/informers/workload_entry.go
- internal/meshes/istio/informers/workload_group.go
- pkg/model/model_converter.go
> fixed broker env and panic

- main.go
- pkg/model/model.go
Added Gorm model foreign key for Index field. (Which is mandated by the Gorm convention)
> minor model fix for index field

- go.mod
- pkg/model/model.go
- pkg/model/model_converter.go
> MESHSYNC schema modified

- README.md
Signed-off-by: aisuko <urakiny@gmail.com>
This PR fixes #3
> Reformat logo address and other static resources

- .github/workflows/build-and-release.yml
- internal/informer/error.go
- internal/informer/informer.go
- internal/pipeline/error.go
- internal/pipeline/global_resource.go
- internal/pipeline/local_resource.go
- meshsync/error.go
- meshsync/handlers.go
> error statements updated

- go.mod
- go.sum
> bumped meshkit

- pkg/model/model.go
- pkg/model/model_converter.go
Resource ID has been released with uuid type. It was int previously.
> replaced id with uuid

- pkg/model/model_converter.go
> fix object parsing

- pkg/model/model.go
> remove delete constructor

- pkg/model/model.go
- pkg/model/model_converter.go
> modified key value store

- meshsync/exec.go
Interactive terminal fixes for Standard input.
> fixes for exec terminal

- README.md
> Added Discuss Forum Link in README.md

- go.mod
- meshsync/exec.go
Panic fixed for stale terminal sessions
> fixes for stale terminal sessions

- README.md
Signed-off-by: Ritvik Shukla <ritvikshukla261@gmail.com>
This PR fixes #68 
> [README]:Added Slack Badge

- internal/config/types.go
- pkg/model/model.go
- pkg/model/model_converter.go
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR adds:
1. pattern resource ID metadata to the meshsync Object
2. extract resource ID from k8s label and place it in the object
> Add pattern resource ID to meshsync object

- meshsync/exec.go
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
This PR will allow different instance of terminal to be open for different users.
> Added userID to NATS subjects for Interactive Terminal

- internal/pipeline/handlers.go
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR fixes #84 
This PR just ignores the redundant updates.
> Ignore redundant updates

- .github/label-commenter-config.yml
- .github/workflows/label-commenter.yml
Signed-off-by: Ayushman Mishra <ayushvidushi01@gmail.com>
Added label-commenter.yml in workflows and label-commenter-config.yml file in .github directory.
This PR fixes #87 
> Added label commenter workflow

- .github/workflows/build-and-release.yml
- go.mod
- go.sum
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
> [CI] update workflow

- .github/workflows/ci.yml
- .golangci.yml
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
> [CI] Fix golanglint-ci action

- .github/workflows/build-and-release.yml
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR fixes #118 
> [CI] Fix docker build action

- internal/config/default_config.go
- meshsync/exec.go
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
> [chore] Support for discovering ReplicaSets

- Dockerfile
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
> Remove amd hardcoding

- .github/workflows/build-and-release.yml
- .github/workflows/ci.yml
- .github/workflows/error-codes-updater.yml
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
This PR cleans up a bit more on the CI workflows, which should help the other open PR https://github.com/meshery/meshsync/pull/149
> [CI] Enhance workflow

- main.go
> fix panic from Meshkit err

- main.go
> fix extranous logging and URL

- pkg/model/model.go
> Change gorm tags for postgres compatibility

- internal/pipeline/handlers.go
> fix missplled variable

- .github/workflows/ci.yml
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
> fix lint issue

- meshsync/exec.go
- meshsync/meshsync.go
Pair PR to https://github.com/meshery/meshery-operator/pull/483
> Updates reduction

- README.md
Inserted build tag in readme.md
The build tag is pointing to [multi-platform.yml](https://github.com/meshery/meshery-istio/blob/master/.github/workflows/multi-platform.yml)
> Inserted build tag in readme.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/ci.md
- .github/ISSUE_TEMPLATE/feature_request.md
Issue #210
I have copied the given information in the docs. I am happy to make any changes if required.
> docs: issue #210 Issue Template Updates for Figma link

- internal/config/default_config.go
Signed-off-by : vadiraj.puranik08@gmail.com 
This PR fixes #217
1:Updated the default_config.go to support ingress resource
> Support for ingress resource in meshsync

- internal/config/default_config.go
This PR fixes #223
Added support for `endpoints`, pattern that should be matched is `endpoints.v1.`
> Add `endpoints` support

- internal/pipeline/handlers.go
- main.go
This PR fixes #218
Disable lint issues for those errors that were stopping `make`.
> Add `nolint` to the errors

- internal/config/default_config.go
> fix crash at discovery stage

- internal/config/default_config.go
Fixes a small typo in `config`.
> fix `syc` typo to `sync`

- CONTRIBUTING.md
- Makefile
Instructions for running meshsync locally
This PR fixes #220 
This PR has additional documentation to enable one run meshsync locally. It also updates the makefile with helper functions to aid in running meshsync locally 
- [ x] Yes, I signed my commits.
> [Docs] Readme: Contributor Instructions and Make Target

- internal/pipeline/pipeline.go
- internal/pipeline/step.go
- meshsync/discovery.go
- meshsync/meshsync.go
> Revert "[Enhancement] Use Streaming Lists when available"

- pkg/model/model.go
> [Fingerprinting] Add support to enable fingerprinting.

- .github/label-commenter-config.yml
> [Fix CI] Add Label Commenter

- internal/config/default_config.go
> add grafana to config

- .github/workflows/ci.yml
- Makefile
- meshsync/exec.go
- meshsync/handlers.go
- meshsync/logstream.go
- pkg/model/model_converter.go
- pkg/model/process.go
fixed some golangci-lint problems
> refactor: replace utils.Marshal/Unmarshal with json.Marshal/json.Unmarshal

- .golangci.yml
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>
> Enable shadow linter in .golangci.yml and remove shadowing check from govet

- internal/config/crd_config_test.go
> Make count of config pipeline dynamic

- README.md
- main.go
This PR adds docs for #355 
As was discussed in slack, adding README description on "snapshot with local file" feature.
Also slightly enhanced input params description in parseFlags.
> feature: 355: snapshot with local file: add README description on new feature

- .github/workflows/build-and-release.yml
- .github/workflows/ci.yml
- .github/workflows/error-codes-updater.yml
- .github/workflows/integration-tests-ci.yml
- Dockerfile
> chore: update Dockerfile and ci pipelines to use go 1.24
