meshsync/logstream.go
pkg/model/log.go

Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
MeshSync will now pass the pod and container name, along with the log data to the NATS client.
This PR fixes [#100 [meshery-extensions]](https://github.com/layer5labs/meshery-extensions/issues/100)

Added primary and secondary refs for logs

---

pkg/model/model.go
pkg/model/model_converter.go
pkg/utils/utils.go

This PR adds support for multicluster by:
1. Annotating discovered resources by the cluster ID in which MeshSync
is running.
2. Attaching cluster ID to the resource IDs, hence identifying the
resource uniquely even in multiple clusters.
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

Support Multi Cluster

---

internal/pipeline/handlers.go

Currently, when the informer(_reflector_ component to be specific) performs _re-listing_ because of a broken watch connection, Meshery won't get some delete events because the `obj` will be of type `DeletedFinalStateUnknown` in those cases. 
This PR ensures that we don't lose a `Delete` event when the watch connection established by the informer breaks for some reason, by sending a _possibly stale_ object rather than not sending anything at all.
This _**may be**_ the reason for #90 and probably related to #100 although I highly doubt that because it is more likely that it's because of the way the clients are handling the events.

Fix: Send Possibly Stale Object on Broken WatchConn to Keep Meshery in Sync

---

helpers/component_info.json
internal/config/default_config.go
internal/config/types.go
internal/pipeline/error.go
internal/pipeline/handlers.go
internal/pipeline/pipeline.go
internal/pipeline/step.go
main.go
meshsync/discovery.go
meshsync/exec.go
meshsync/handlers.go
meshsync/meshsync.go

This PR makes leverages the data that are in the `Stores` that `SharedInformers` maintain so that a client, such as Meshery Server does not have to ask MeshSync to resync every time it needs to replay the old events to arrive at the current state of the cluster. I have also refactored some parts of the codebase.
- There are some places where I have added TODO statements since they require changes to be done in MeshKit. Those will be addressed in a different PR.
- Error codes are yet to be created for the functionalities that has been introduced in this PR, which would be addressed in a different PR.

[Feat] Make use of the data stored in SharedInformer stores and refactor codebase

---

internal/config/default_config.go

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
- This PR updates the pipeline config to add support for 2 new k8s API-resources for Meshsync to be aware of while looking for objects in the cluster.
- API-resources:
- PersistentVolumes
- PersistentVolumeClaims
- Will allow the MeshMap to show these on the visualizer canvas
Please check the supporting PR on meshery-extension repo as well

[chore] Support for PersistentVolumes and PersistentVolumeClaims

---

internal/config/default_config.go
internal/pipeline/step.go
meshsync/handlers.go

1. The state was not being synced as WaitForCache was being called after the informer had already started. This PR calls WaitForCache only before starting the informer. NOTE: It is not related to resync.
2. Due to missing CRDs, creating informer for istio resources results in error. This PR removes those extra resources

Fix failing state sync and remove extranous error log

---

internal/config/default_config.go

This PR partially fixes #225.
In this pr, I will add more kubernetes resource types.

Add `kubernetes resources` support

---

.github/workflows/build-and-release.yml
.github/workflows/ci.yml
.gitignore
.golangci.yml
Makefile
meshsync/discovery.go
meshsync/exec.go
meshsync/handlers_test.go

* Update `.golangci.config`, make it as same as `meshery-operator`. It is really useful for check the potential issues of Kubernetes related project. We do not enable all checker or disable all. We should keep the configuration readable by maintainers.
*  This PR also fixed some of issues were checked by `golangci-lint` of the code.
* Add code `coverage` to the CI.

Add golangci-lint's cconfiguration

---

.gitignore
meshsync/handlers.go
meshsync/handlers_test.go
pkg/model/model.go
pkg/model/model_converter.go

Objects -> KubernetesResources
ResourceSpec -> KubernetesResourceSpec
ResourceObjectMeta -> KubernetesResourceObjectMeta
ResourceStatus -> KubernetesResourceStatus
KeyValue -> KubernetesKeyValue
According to slides in [Meshery Architecture Deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.ga925ebd4ad_0_230)

[chore] Rename MeshSync Tables.

---

Makefile

This pull request standardizes Meshsyncs Makefile grouping commands and making descriptive comments on 
each target to make engagement with Meshsync standard to encourage wider participation
Simple reorganization and commenting of Makefile

#Docs Standardize Makefile

---

go.mod
internal/config/crd_config.go
main.go
meshsync/logstream.go

The log stream once created was not getting closed causing issues when the user again tried to stream logs for the same pod.
The PR ensure the log stream is appropriately closed when 'stop' signal is received.

fix init and close of logs stream

---

.github/workflows/build-and-release.yml
.github/workflows/ci.yml
.github/workflows/error-codes-updater.yml
Dockerfile
go.mod

upgrading `meshsync`
fixes: meshery/meshery#12829

Bump `meshsync` Go version to 1.23 in workflows, Dockerfile, and go.mod

---

Dockerfile

Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

Update Dockerfile to use uppercase 'AS' for builder stage

---

internal/config/default_config.go

Add support for additional Kubernetes resource types in default configuration

---

pkg/model/model.go

add model name in the kubernetesResource struct for return the model name with the kind and count in summary api

---

README.md

Signed-off-by: miacycle <184569369+miacycle@users.noreply.github.com>
Meshery has a new GitHub Organization to add to the list of orgs hyperlinked under the "help wanted" label hyperlink.

update README.md to include 'meshery-extensions' in help-wanted issues link

---

integration-tests/default_cluster_test_cases_test.go
main.go

This PR fixes an issue with undefined flag --broker-url
After we did https://github.com/meshery/meshsync/releases/tag/v0.8.7 meshsync is now failing to start in deployment with an error: `flag provided but not defined: -broker-url` 
the actual code is not using this param, it uses it from env variable.
Added stub for broker-url for compatibility.

fix: flag provided but not defined: -broker-url

---

pkg/lib/meshsync/meshsync.go

This PR fixes  the behavior of meshsync to execute watch CRDs code only if CRDs are present in the cluster. 

feature: meshsync as a library: perform crd watch only if they present in the cluster

---

integration-tests/meshsync_as_binary_with_k8s_cluster_test_cases_mode_a_broker_test.go
integration-tests/meshsync_as_binary_with_k8s_cluster_test_cases_mode_b_file_test.go
internal/config/pluralise.go
internal/config/pluralise_test.go
internal/config/types.go
internal/pipeline/handlers.go
internal/pipeline/pipeline.go
internal/pipeline/step.go
main.go
meshsync/discovery.go
meshsync/meshsync.go
pkg/lib/meshsync/meshsync.go
pkg/lib/meshsync/options.go

This PR fixes updates the output filtration which is used in otput mode file.
- remove global options and propagate options from Run function; 
- add options to libmeshsync to be able to provide list of namespaces and list of resources to which restrict resource output (this will be convenient to use from krew plugin);
- allow multiple namespace instead of single namespace;
- do not subscribe to informer for resources which are not required to output; 

Chore simple output resources filtration

---

meshsync/handlers.go

This PR fixes #434 
move the content of WatchCRDs to watchCRDsIteration
and repeat in a loop call to watchCRDsIteration until close channel is closed;
there is no need in exponential retry as there  we are doing it for case when crdWatcher.ResultChan() is closed. Which happens after some time (probably of innactivity), we only need to continue to watch, hence resubscribe. 

chore: resubscribe to watch crds if result channel of informer is closed

---

.github/workflows/integration-tests-ci.yml

- we don have golden files;
- add go.mod go.sum to trigger conditions, so that dependabot pr will be covered with integration tests :white_check_mark: . 

chore: trigger integration tests on changes to go.mod go.sum, so that dependabot prs will be covered
